/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author User
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btValidarCpf = new javax.swing.JButton();
        btGerarCpf = new javax.swing.JButton();
        btGerarDv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btValidarCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btValidarCpf.setText("VALIDAR CPF");
        btValidarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidarCpfActionPerformed(evt);
            }
        });

        btGerarCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGerarCpf.setText("GERAR CPF ALEATÓRIO");
        btGerarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarCpfActionPerformed(evt);
            }
        });

        btGerarDv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGerarDv.setText("GERAR DIGITO VERIFICADOR");
        btGerarDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDvActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ESCOLHA UMA OPÇÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGerarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btGerarDv)
                            .addComponent(btValidarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(btValidarCpf)
                .addGap(32, 32, 32)
                .addComponent(btGerarDv)
                .addGap(37, 37, 37)
                .addComponent(btGerarCpf)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValidarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidarCpfActionPerformed
        // TODO add your handling code here:
         FormValidarCpf num = new FormValidarCpf(this, true); 
        num.setLocationRelativeTo(num);
        num.setVisible(true);
                                      
    }//GEN-LAST:event_btValidarCpfActionPerformed

    private void btGerarDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDvActionPerformed
        // TODO add your handling code here:
      FormGerarDigitoVerificador num = new FormGerarDigitoVerificador(this, true); 
        num.setLocationRelativeTo(num);
        num.setVisible(true);
                                   
    }//GEN-LAST:event_btGerarDvActionPerformed

    private void btGerarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarCpfActionPerformed
        // TODO add your handling code here:
        FormGerarCpfAleatorio num = new FormGerarCpfAleatorio(this, true); 
        num.setLocationRelativeTo(num);
        num.setVisible(true);
    }//GEN-LAST:event_btGerarCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarCpf;
    private javax.swing.JButton btGerarDv;
    private javax.swing.JButton btValidarCpf;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
